name: MLOps Automation

on:
  push:
    branches: [master]         # Trigger on pushes to the main branch
  schedule:
    - cron: '0 * * * *'      # Trigger every hour (UTC)
  workflow_dispatch:         # Allow manual triggering

jobs:
  mlops:
    runs-on: ubuntu-latest

    env:
        FS_API_KEY: ${{ secrets.FS_API_KEY }}
        FS_PROJECT_NAME: ${{ secrets.FS_PROJECT_NAME }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
        WANDB_PROJECT_NAME: ${{ secrets.WANDB_PROJECT_NAME }}
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Debug print
      run: |
        echo "FS_PROJECT_NAME is: $FS_PROJECT_NAME"
        echo "API Key starts with: ${FS_API_KEY:0:30}"
      env:
        FS_API_KEY: ${{ secrets.FS_API_KEY }}
        FS_PROJECT_NAME: ${{ secrets.FS_PROJECT_NAME }}


    
